const { chromium } = require('../../work-tests/browser/node_modules/playwright');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'msedge',headless:true});
 const page = await browser.newPage();
 page.on('dialog', d => d.accept());
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 const base=process.env.VIDEONOTE_TEST_URL || 'http://localhost:5189';
 await page.goto(base + '/prompts');
 const builtin=page.locator('.item').filter({hasText:/大纲提取(?! 副本)/});
 await builtin.waitFor();
 assert.equal(await builtin.getByRole('button',{name:'删除',exact:true}).count(),0);
 await builtin.getByRole('button',{name:'复制',exact:true}).click();
 const copied=page.locator('.item').filter({hasText:'大纲提取 副本'});
 await copied.waitFor();
 await copied.getByRole('button',{name:'编辑',exact:true}).click();
 await page.getByLabel('模板名称',{exact:true}).fill('UI Template');
 await page.getByLabel('模板内容',{exact:true}).fill('Snapshot instructions from UI.');
 await page.getByRole('button',{name:'保存模板',exact:true}).click();
 await page.locator('.item').filter({hasText:'UI Template'}).waitFor();
 await page.reload();
 await page.locator('.item').filter({hasText:'UI Template'}).waitFor();
 await page.getByRole('button',{name:'新建模板',exact:true}).click();
 await page.getByLabel('模板名称',{exact:true}).fill('UI Temporary');
 await page.getByLabel('模板内容',{exact:true}).fill('Delete me.');
 await page.getByRole('button',{name:'保存模板',exact:true}).click();
 const temp=page.locator('.item').filter({hasText:'UI Temporary'});
 await temp.waitFor();
 await temp.getByRole('button',{name:'删除',exact:true}).click();
 await page.locator('.item').filter({hasText:'UI Temporary'}).waitFor({state:'detached'});
 await page.goto(base + '/tasks/new');
 await page.getByLabel('提示词模板',{exact:true}).selectOption({label:'UI Template'});
 await page.locator('#video-file').setInputFiles(path.resolve('tests/fixtures/sample.mkv'));
 await page.getByRole('button',{name:'上传并创建任务'}).click();
 await page.waitForURL(/\/tasks\/[0-9a-f-]{36}$/, {timeout:60000});
 await page.getByRole('heading',{name:'sample.mkv'}).waitFor();
 const tasks=await (await page.request.get(base+'/api/tasks')).json();
 const task=tasks.find(t=>t.originalFileName==='sample.mkv');
 assert.ok(task.promptTemplateId);
 await page.goto(base + '/prompts');
 await page.locator('.item').filter({hasText:'UI Template'}).getByRole('button',{name:'删除',exact:true}).click();
 await page.locator('.item').filter({hasText:'UI Template'}).waitFor({state:'detached'});
 const saved=await (await page.request.get(base+'/api/tasks/'+task.id)).json();
 assert.equal(saved.promptTemplateId,null);
 assert.equal(saved.promptContentSnapshot,'Snapshot instructions from UI.');
 await page.screenshot({path:'work-tests/browser/prompts.png',fullPage:true});
 await page.goto(base + '/tasks');
 await page.locator('.item').filter({hasText:'sample.mkv'}).getByRole('button',{name:'删除任务及物料'}).click();
 await page.getByText('暂无任务。',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: builtin protection/copy, custom CRUD, reload, task selection and retained snapshot');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
