const { chromium } = require('../../work-tests/browser/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'msedge',headless:true});
 try {
  const page = await browser.newPage();
  page.on('dialog', d => d.accept());
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  const base=process.env.VIDEONOTE_TEST_URL || 'http://localhost:5189';
  const provider = name => page.locator('.item').filter({has:page.getByText(name,{exact:true})});
  await page.goto(base + '/settings');
  await provider('DeepSeek').waitFor();
  await provider('DeepSeek').getByText('ENV DEEPSEEK_API_KEY',{exact:true}).waitFor();
  await provider('DeepSeek').getByRole('button',{name:'管理模型'}).click();
  await page.getByText('deepseek-v4-flash-vision-exp',{exact:true}).waitFor();
  await page.getByRole('button',{name:'新建提供商',exact:true}).click();
  await page.getByLabel('名称',{exact:true}).fill('UI Smoke');
  await page.getByLabel('协议',{exact:true}).selectOption('gemini-native');
  await page.getByLabel('Base URL').fill('https://example.com/v1');
  await page.getByRole('button',{name:'保存提供商'}).click();
  await provider('UI Smoke').waitFor();
  await provider('UI Smoke').getByText('Gemini 原生',{exact:true}).waitFor();
  await provider('UI Smoke').getByRole('button',{name:'管理模型'}).click();
  await page.getByRole('button',{name:'新建模型',exact:true}).click();
  await page.getByLabel('Model ID').fill('smoke-model');
  await page.getByLabel('上下文窗口（token）',{exact:true}).fill('2048');
  const capabilities=['思考','工具调用','流式','图片','音频','视频'];
  for (const capability of capabilities) await page.getByLabel(capability,{exact:true}).check();
  await page.getByRole('button',{name:'保存模型'}).click();
  await page.getByText('smoke-model',{exact:true}).waitFor();
  await page.reload();
  await provider('UI Smoke').waitFor();
  await provider('UI Smoke').getByRole('button',{name:'编辑提供商'}).click();
  assert.equal(await page.getByLabel('协议',{exact:true}).inputValue(),'gemini-native');
  await page.getByLabel('名称',{exact:true}).fill('UI Updated');
  await page.getByLabel('协议',{exact:true}).selectOption('openai-compatible');
  await page.getByRole('button',{name:'保存提供商'}).click();
  await provider('UI Updated').waitFor();
  await provider('UI Updated').getByText('OpenAI 兼容',{exact:true}).waitFor();
  await provider('UI Updated').getByRole('button',{name:'管理模型'}).click();
  await page.getByRole('button',{name:'编辑模型',exact:true}).click();
  assert.equal(await page.getByLabel('上下文窗口（token）',{exact:true}).inputValue(),'2048');
  for (const capability of capabilities) assert.equal(await page.getByLabel(capability,{exact:true}).isChecked(),true);
  await page.getByLabel('Model ID').fill('updated-model');
  await page.getByRole('button',{name:'保存模型'}).click();
  await page.getByText('updated-model',{exact:true}).waitFor();
  await page.screenshot({path:'work-tests/browser/settings.png',fullPage:true});
  await page.getByRole('button',{name:'删除模型',exact:true}).click();
  await page.getByText('该提供商尚未添加模型。').waitFor();
  await provider('UI Updated').getByRole('button',{name:'删除提供商',exact:true}).click();
  await provider('UI Updated').waitFor({state:'detached'});
  await provider('DeepSeek').waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: DeepSeek preset; provider/model CRUD, both protocols, all capability mappings; no browser errors');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
