const { chromium } = require('../../work-tests/browser/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'msedge',headless:true});
 const page = await browser.newPage();
 page.on('dialog', d => d.accept());
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto((process.env.VIDEONOTE_TEST_URL || 'http://localhost:5189') + '/settings');
 await page.getByRole('button',{name:'新建提供商',exact:true}).click();
 await page.getByLabel('名称',{exact:true}).fill('UI Smoke');
 await page.getByLabel('Base URL').fill('https://example.com/v1');
 await page.getByRole('button',{name:'保存提供商'}).click();
 await page.getByRole('cell',{name:'UI Smoke',exact:true}).waitFor();
 await page.getByRole('button',{name:'管理模型'}).click();
 await page.getByRole('button',{name:'新建模型',exact:true}).click();
 await page.getByLabel('Model ID').fill('smoke-model');
 await page.getByLabel('图片',{exact:true}).check();
 await page.getByRole('button',{name:'保存模型'}).click();
 await page.getByRole('cell',{name:'smoke-model',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('cell',{name:'UI Smoke',exact:true}).waitFor();
 await page.getByRole('button',{name:'编辑提供商'}).click();
 await page.getByLabel('名称',{exact:true}).fill('UI Updated');
 await page.getByRole('button',{name:'保存提供商'}).click();
 await page.getByRole('cell',{name:'UI Updated',exact:true}).waitFor();
 await page.getByRole('button',{name:'管理模型'}).click();
 await page.getByRole('button',{name:'编辑模型',exact:true}).click();
 await page.getByLabel('Model ID').fill('updated-model');
 await page.getByRole('button',{name:'保存模型'}).click();
 await page.getByRole('cell',{name:'updated-model',exact:true}).waitFor();
 await page.screenshot({path:'work-tests/browser/settings.png',fullPage:true});
 await page.getByRole('button',{name:'删除模型',exact:true}).click();
 await page.getByText('该提供商尚未添加模型。').waitFor();
 await page.getByRole('button',{name:'删除提供商',exact:true}).click();
 await page.getByText('暂无提供商，请先添加。').waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: provider/model create, edit, reload, delete; no browser errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
