const { chromium } = require('../../work-tests/browser/node_modules/playwright');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'msedge',headless:true});
 const page = await browser.newPage();
 page.on('dialog', d => d.accept());
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 const base = process.env.VIDEONOTE_TEST_URL || 'http://localhost:5189';
 await page.goto(base + '/tasks/new');
 await page.locator('#video-file').setInputFiles(path.resolve('tests/fixtures/subtitles.srt'));
 await page.getByRole('button',{name:'上传并创建任务'}).click();
 await page.getByText('视频扩展名不受支持。',{exact:true}).waitFor();
 await page.locator('#video-file').setInputFiles(path.resolve('work-tests/large.mp4'));
 await page.getByRole('button',{name:'上传并创建任务'}).click();
 await page.waitForURL(/\/tasks\/[0-9a-f-]{36}$/, {timeout:120000});
 await page.getByRole('heading',{name:'large.mp4'}).waitFor();
 await page.goto(base + '/tasks');
 await page.getByRole('link',{name:'large.mp4',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('link',{name:'large.mp4',exact:true}).waitFor();
 await page.screenshot({path:'work-tests/browser/upload.png',fullPage:true});
 await page.locator('.item').filter({hasText:'large.mp4'}).getByRole('button',{name:'删除任务及物料'}).click();
 await page.getByText('暂无任务。',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: native browser 320 MiB upload, extension validation, persistence and deletion');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
