// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoNote.Server.Data;

#nullable disable

namespace VideoNote.Server.Data.Migrations
{
    [DbContext(typeof(VideoNoteDbContext))]
    [Migration("20260909071306_SeedDeepSeekDefaults")]
    partial class SeedDeepSeekDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("VideoNote.Server.Data.Entities.AnalysisTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptContentSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultText")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelConfigId");

                    b.HasIndex("PromptTemplateId");

                    b.ToTable("AnalysisTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnalysisTasks_ProgressPercent_Range", "ProgressPercent >= 0 AND ProgressPercent <= 100");
                        });
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTaskId");

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.ModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsReasoning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsToolCalling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsVideo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ModelId")
                        .IsUnique();

                    b.ToTable("ModelConfigs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ModelConfigs_ContextWindow_Positive", "ContextWindow > 0");
                        });
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Content = "根据视频内容生成层次清晰的大纲。使用 Markdown 标题和列表，按主题或时间顺序组织。仅在物料提供时间信息时标注时间戳；不编造视频未提供的信息。",
                            CreatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBuiltIn = true,
                            Name = "大纲提取",
                            UpdatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Content = "提取视频的关键观点、结论和支持依据。使用 Markdown 列表，区分事实、观点与不确定内容；仅在物料提供时标注相关时间戳。",
                            CreatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBuiltIn = true,
                            Name = "重点提取",
                            UpdatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Content = "用中文概述视频主题、主要内容和结论。输出简洁的 Markdown 摘要，保留必要背景和限制，不添加视频未支持的信息。",
                            CreatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBuiltIn = true,
                            Name = "摘要",
                            UpdatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Content = "从视频提取核心关键词、术语及简短解释。使用 Markdown 表格，按重要程度排序，解释应以视频内容为依据。",
                            CreatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBuiltIn = true,
                            Name = "关键词",
                            UpdatedAtUtc = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.AnalysisTask", b =>
                {
                    b.HasOne("VideoNote.Server.Data.Entities.ModelConfig", "ModelConfig")
                        .WithMany("AnalysisTasks")
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VideoNote.Server.Data.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany("AnalysisTasks")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelConfig");

                    b.Navigation("PromptTemplate");
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.ConversationMessage", b =>
                {
                    b.HasOne("VideoNote.Server.Data.Entities.AnalysisTask", "AnalysisTask")
                        .WithMany("Messages")
                        .HasForeignKey("AnalysisTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisTask");
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.ModelConfig", b =>
                {
                    b.HasOne("VideoNote.Server.Data.Entities.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.AnalysisTask", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.ModelConfig", b =>
                {
                    b.Navigation("AnalysisTasks");
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.PromptTemplate", b =>
                {
                    b.Navigation("AnalysisTasks");
                });

            modelBuilder.Entity("VideoNote.Server.Data.Entities.Provider", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
